version: 2

javaImage: &javaImage ircleci/openjdk:8-jdk

openjdk: &openjdk
  docker:
    - image: *javaImage
  working_directory: ~/spring-recipe-app

package: &package
  name: Package
  command: mvn package -DskipTests

unitTest:  &unitTest
  name: Unit test
  command: mvn test

restoreCache: &restoreCache
  key: spring-recipe-app-{{ checksum "pom.xml" }}

saveCache: &saveCache
  paths:
    - ~/.m2
  key: spring-recipe-app-{{ checksum "pom.xml" }}